### ISSUE TITLE
Failed create CA private key

### ISSUE THREAD

**Issue by xakod** [TinCanTech/easyrsa-plus#1]
> PS C:\Program Files\OpenVPN\easy-rsa> .\EasyRSA-Start.bat
> 
> Welcome to the EasyRSA 3 Shell for Windows.
> Easy-RSA 3 is available under a GNU GPLv2 license.
> 
> Invoke './easyrsa' to call the program. Without commands, help is displayed.
> 
> EasyRSA Shell
> easyrsa build-ca
> 
> Note: using Easy-RSA configuration from: C:/Program Files/OpenVPN/easy-rsa/vars
> Using SSL: openssl OpenSSL 1.1.1a  20 Nov 2018
> path = C:/Program Files/OpenVPN/easy-rsa/pki/easy-rsa-3456.a18896/tmp.XXXXXX
> lpPathBuffer = C:\Users\User\AppData\Local\Temp\
> szTempName = C:\Users\User\AppData\Local\Temp\tmp5C77.tmp
> path = C:\Users\Anton\AppData\Local\Temp\tmp5C77.tmp
> fd = 3
> path = C:/Program Files/OpenVPN/easy-rsa/pki/easy-rsa-3456.a18896/tmp.XXXXXX
> lpPathBuffer = C:\Users\User\AppData\Local\Temp\
> szTempName = C:\Users\User\AppData\Local\Temp\tmp5D23.tmp
> path = C:\Users\Anton\AppData\Local\Temp\tmp5D23.tmp
> fd = 3
> path = C:/Program Files/OpenVPN/easy-rsa/pki/easy-rsa-3456.a18896/tmp.XXXXXX
> lpPathBuffer = C:\Users\User\AppData\Local\Temp\
> szTempName = C:\Users\User\AppData\Local\Temp\tmp5DDF.tmp
> path = C:\Users\User\AppData\Local\Temp\tmp5DDF.tmp
> fd = 3
> 
> Enter New CA Key Passphrase:
> Re-Enter New CA Key Passphrase:
> Extra arguments given.
> genrsa: Use -help for summary.
> 
> Easy-RSA error:
> 
> Failed create CA private key

I initialized pki before build-ca of course.

**Comment by TinCanTech** [comment]
See `./easyrsa help build-ca`

Closed as **user error**.
